/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZDCWk5WDy0J
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "../components/ui/input"
import { Button } from "../components/ui/button"
import React from "react"

export function SubmitLink() {
  return (
    <div className="flex items-center justify-center h-screen">
      <div className="bg-card p-8 rounded-lg shadow-lg w-full max-w-md">
        <div className="space-y-4">
          <h2 className="text-2xl font-bold text-card-foreground">Submit Your Artifact</h2>
          <p className="text-muted-foreground">Enter the link to your artifact below to share it with us.</p>
          <div className="flex items-center space-x-2">
            <Input type="text" placeholder="Enter artifact link..." className="flex-1" />
            <Button>Submit</Button>
          </div>
        </div>
      </div>
    </div>
  )
}
